language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - python3 abstain/manage.py makemigrations
  - python3 abstain/manage.py migrate

notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always
